# Configure URL. if using gh-pages https://github.com/<username>/hugo-universal-theme URL: https://<username>.github.io/hugo-universal-theme/
baseurl = "https://miraitech.github.io/" 
title = "Mirai Tech"
theme = "hugo-universal-theme"
# themesDir = "../.."

languageCode = "ja-jp"

# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "ja"

# Enable comments by entering your Disqus shortname
disqusShortname = "guest"

# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# number of words of summarized post content (default 70)
summaryLength = 30

# Define the number of posts per page
paginate = 5

# not pluralize title pages by default
pluralizelisttitles = false

[menu]


# Main menu
#----------------------------------------------------
[[menu.main]]
    name       = "ホーム"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

#[[menu.main]]
#    name       = "Option 1: Default Page"
#    url        = "/"
#    weight     = 1
#    parent     = "menu.home"

#[[menu.main]]
#    name       = "Option 2: Application"
#    url        = "/"
#    weight     = 2
#    parent     = "menu.home"

#[[menu.main]]
#    name       = "Option 3: Startup"
#    url        = "/"
#    weight     = 3
#    parent     = "menu.home"


#----------------------------------------------------
[[menu.main]]
    name       = "事業内容"
    identifier = "menu.features"
    url        = "/img/template-easy-customize.png"
    weight     = 2

[[menu.main]]
    name       = "事業内容"
    identifier = "section.shortcodes"
    url        = ""
    weight     = 1
    parent     = "menu.features"
    post       = 1

[[menu.main]]
    name       = "サービス内容"
    identifier = "section.headervariations"
    url        = ""
    weight     = 2
    parent     = "menu.features"
    post       = 2

[[menu.main]]
    name       = "事業①"
    url        = ""
    weight     = 1
    parent     = "section.shortcodes"

[[menu.main]]
    name       = "事業②"
    url        = ""
    weight     = 2
    parent     = "section.shortcodes"

[[menu.main]]
    name       = "事業③"
    url        = ""
    weight     = 3
    parent     = "section.shortcodes"

[[menu.main]]
    name       = "事業④"
    url        = ""
    weight     = 4
    parent     = "section.shortcodes"

[[menu.main]]
    name       = "事業⑤"
    url        = ""
    weight     = 5
    parent     = "section.shortcodes"

[[menu.main]]
    name       = "事業⑥"
    url        = ""
    weight     = 6
    parent     = "section.shortcodes"

[[menu.main]]
    name       = "事業⑦"
    url        = ""
    weight     = 7
    parent     = "section.shortcodes"

[[menu.main]]
    name       = "事業⑧"
    url        = ""
    weight     = 8
    parent     = "section.shortcodes"

[[menu.main]]
    name       = "サービス①"
    url        = ""
    weight     = 1
    parent     = "section.headervariations"

[[menu.main]]
    name       = "サービス②"
    url        = ""
    weight     = 2
    parent     = "section.headervariations"

[[menu.main]]
    name       = "サービス③"
    url        = ""
    weight     = 3
    parent     = "section.headervariations"


#------------------------------------------------
[[menu.main]]
    name       = "会社概要"
    identifier = "menu.portfolio"
    url        = "/img/template-homepage.png"
    weight     = 3

[[menu.main]]
    name       = "会社概要"
    identifier = "section.portfolio"
    url        = ""
    weight     = 1
    parent     = "menu.portfolio"
    post       = 1

[[menu.main]]
    name       = "社長CEO挨拶"
    url        = ""
    weight     = 1
    parent     = "section.portfolio"

[[menu.main]]
    name       = "企業理念"
    url        = ""
    weight     = 2
    parent     = "section.portfolio"

[[menu.main]]
    name       = "企業行動指針"
    url        = ""
    weight     = 3
    parent     = "section.portfolio"

[[menu.main]]
    name       = "経営方針・経営計画"
    url        = ""
    weight     = 4
    parent     = "section.portfolio"

[[menu.main]]
    name       = "役員紹介"
    url        = ""
    weight     = 5
    parent     = "section.portfolio"

[[menu.main]]
    name       = "組織図"
    url        = ""
    weight     = 6
    parent     = "section.portfolio"

[[menu.main]]
    name       = "歴史・沿革"
    url        = ""
    weight     = 7
    parent     = "section.portfolio"

[[menu.main]]
    name       = "広告・動画ライブラリー"
    url        = ""
    weight     = 8
    parent     = "section.portfolio"

[[menu.main]]
    name       = "国内関連会社"
    identifier = "section.about"
    url        = ""
    weight     = 2
    parent     = "menu.portfolio"
    post       = 2

[[menu.main]]
    name       = "関東本社"
    url        = ""
    weight     = 1
    parent     = "section.about"

[[menu.main]]
    name       = "関西支社"
    url        = ""
    weight     = 2
    parent     = "section.about"

[[menu.main]]
    name       = "海外子会社"
    identifier = "section.marketing"
    url        = ""
    weight     = 3
    parent     = "menu.portfolio"
    post       = 2

[[menu.main]]
    name       = "未来科技信息技术股份有限公司（北京）"
    url        = ""
    weight     = 1
    parent     = "section.marketing"


#-----------------------------------------------------------------
[[menu.main]]
    name       = "パートナー企業"
    identifier = "menu.allpages"
    url        = "/img/template-partner.png"
    weight     = 4

[[menu.main]]
    name       = "国内パートナー"
    identifier = "section.ap-home"
    url        = ""
    weight     = 1
    parent     = "menu.allpages"
    post       = 1

[[menu.main]]
    name       = "パートナー①"
    url        = ""
    weight     = 1
    parent     = "section.ap-home"

[[menu.main]]
    name       = "パートナー②"
    url        = ""
    weight     = 2
    parent     = "section.ap-home"
    post       = 1

[[menu.main]]
    name       = "パートナー③"
    url        = ""
    weight     = 3
    parent     = "section.ap-home"
    post       = 1

[[menu.main]]
    name       = "パートナー④"
    url        = ""
    weight     = 4
    parent     = "section.ap-home"
    post       = 1

[[menu.main]]
    name       = "海外パートナー"
    identifier = "section.ap-blog"
    url        = "/blog/"
    weight     = 1
    parent     = "menu.allpages"
    post       = 2

[[menu.main]]
    name       = "パートナーXX"
    url        = "/blog/"
    weight     = 1
    parent     = "section.ap-blog"

#----------------------------------------------
[[menu.main]]
    name       = "お知らせ"
    identifier = "menu.blog"
    url        = "/blog/"
    weight     = 5

[[menu.main]]
    name       = "よくある質問"
    identifier = "menu.faq"
    url        = "/faq/"
    weight     = 6

[[menu.main]]
    name       = "お問い合わせ"
    identifier = "contact"
    url        = "/contact/"
    weight     = 7


# Topbar social links menu
[[menu.topbar]]
    weight = 1
    name = "Phone"
    url = "tel:03-6666-9232"
    pre = "<i class='fas fa-2x fa-phone'></i>"

[[menu.topbar]]
    weight = 2
    name = "Email"
    url = "mailto:contact@miraitech.com"
    pre = "<i class='fas fa-2x fa-envelope'></i>"

[[menu.topbar]]
    weight = 3
    name = "Facebook"
    url = "http://facebook.com"
    pre = "<i class='fab fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 4
    name = "Twitter"
    url = "http://twitter.com"
    pre = "<i class='fab fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 5
    name = "GitHub"
    url = ""
    pre = "<i class='fab fa-2x fa-github'></i>"



[params]
    viewMorePostLink = "/blog/"
    author = ""
    defaultKeywords = ["devcows", "hugo", "go"]
    mainSections = ["blog"]
    defaultDescription = "Site template made by Devcows using Hugo"

    # Social media
    facebook_site = ""         # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = ""          # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/sharing-default.png"

    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    enableGoogleMaps = true
    googleMapsApiKey = "AIzaSyAv7Sza8NSp9_l_g8G2vlo0H4ydEPn_2jY"

    latitude = "35.6965778"
    longitude = "139.7639829"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 50 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - register your account to https://formspree.io/register
    # - login and create new form
    # - set your form's endpoint url under 'formspree_action' below
    # - upload the generated site to your server
    # - test a dummy email yourself
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io endpoint url
    formspree_action = "https://formspree.io/"
    contact_form_ajax = false

    # Formspree form supports Google reCAPTCHA Key (type v2).
    # If you use this feature, you should enable reCAPTCHA feature in the Formspree dashboard.
    #
    # By default, Formspree use a redirect page for recaptcha widget.
    # If you use a recaptcha widget in your contact page, you should do next steps.
    # (if you don't want, skip these steps)
    #
    #   1. register your site on Google recaptcha admin page: https://www.google.com/recaptcha/admin
    #   2. select reCAPTCHA v2 and checkbox widget type.
    #   3. remember site key and secret key.
    #   4. enter secret key into "Custom reCAPTCHA Key" field in your Formspree form setting page.
    #   5. change `enableRecaptchaInContactForm` is to true
    #   6. enter site key into `googleRecaptchaKey` to enable a recaptcha widget in your page.
    #
    enableRecaptchaInContactForm = false
    googleRecaptchaKey = "site_key_for_google_recaptcha"

    about_us = "<p>ご意見やご質問がございましたら、</p><p>問い合わせフォームよりお気軽にお問い合わせください。</p>"
    copyright = "Copyright(C) Mirai Tech Co., Ltd. All Rights Reserved"

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    dropdown_mouse_over = false

    disabled_logo = false
    logo_text = "Mirai Tech Co., Ltd."

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    contact_url = "/contact"
    address = """<p class="text-uppercase"><strong>株式会社 MIRAI TECH</strong>
        <br>東京都千代田区神田駿河台1-5-6 713号室
        <br>Tel: 03-6666-9232
        <br>FAX: 03-6666-9767
      </p>
      """

[permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Contact us on Tel: 03-6666-9232 or FAX: 03-6666-9767</p>
      <p class="hidden-md hidden-lg"><a href="tel:03-6666-9232" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
      <a href="mailto:contact@miraitech.com" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carouselCustomers]
    items = 6
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselTestimonials]
    items = 4
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more information take a look at the README.
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.features]
    enable = true
    cols = 3     # Default: 3, Available values 2,3,4,6
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more information take a look at the README.

[params.testimonials]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more information take a look at the README.
    title = "個性が豊富なチームメンバー"
    subtitle = "メンバーからの一言"

[params.see_more]
    enable = true
    icon = "far fa-file-alt"
    title = "Do you want to see more?"
    subtitle = "弊社の代表製品をはじめ、幅広い分野に携わっております。詳細は事業内容を御覧ください。"
    link_text = "事業内容を確認"
    link_url = "#"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more information take a look at the README.
    title = "パートナー企業"
    subtitle = ""

[params.recent_posts]
    enable = true
    hide_summary = false
    title = "お知らせ"
    subtitle = ""

[params.footer.recent_posts]
    enable = true

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"

